# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  S3_CLIENT_BUCKET_NAME: padakmon-client-bucket

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      working-directory: ./client

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3
    
    - name: Use Node.js 18.x to build
      uses: actions/setup-node@v2
      with:
        node-version: 18.x
        
    - name: Install modules
      run: npm install --save-dev prettier --legacy-peer-deps
      working-directory: ${{ env.working-directory }}

    - name: Set .env
      run: |
        touch ${{ env.working-directory }}/.env
        echo "REACT_APP_API_URL=${{ secrets.EC2_URL }}" > ${{ env.working-directory }}/.env
      
    - name: Build project
      run: npm run build
      working-directory: ${{ env.working-directory }}
      
    - name: Deploy
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        aws s3 cp \
            --recursive \
            --region ap-northeast-2 \
            ./${{ env.working-directory }}/build s3://$S3_CLIENT_BUCKET_NAME
        
        

